services:
  - type: web
    name: two-registers-web
    env: static
    buildCommand: npm install --legacy-peer-deps && npm run build
    staticPublishPath: build
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
