services:
  - type: web
    name: two-registers-web
    env: static
    buildCommand: cd frontend && npm ci && npm run build
    staticPublishPath: frontend/dist
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
